ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS finance_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS finance_tan numeric NOT NULL DEFAULT 7.9,
  ADD COLUMN IF NOT EXISTS finance_terms jsonb NOT NULL DEFAULT '[24,36,48,60,72]'::jsonb,
  ADD COLUMN IF NOT EXISTS finance_default_term integer NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS finance_down_default_pct integer NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS finance_down_max_pct integer NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS finance_title text NOT NULL DEFAULT 'Calcola la rata',
  ADD COLUMN IF NOT EXISTS finance_disclaimer text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_eyebrow text NOT NULL DEFAULT 'Pompei · Napoli',
  ADD COLUMN IF NOT EXISTS hero_title text NOT NULL DEFAULT 'Auto di qualità.
Prezzi onesti.',
  ADD COLUMN IF NOT EXISTS hero_subtitle text NOT NULL DEFAULT 'Usato selezionato e controllato. Vieni a provarlo o prenota un appuntamento in pochi secondi.',
  ADD COLUMN IF NOT EXISTS hero_cta_label text NOT NULL DEFAULT 'Vedi il parco auto',
  ADD COLUMN IF NOT EXISTS hero_show_logo boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hero_logo_height integer NOT NULL DEFAULT 160,
  ADD COLUMN IF NOT EXISTS footer_logo_path text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS footer_logo_height integer NOT NULL DEFAULT 128,
  ADD COLUMN IF NOT EXISTS footer_note text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS font_heading text NOT NULL DEFAULT 'Oswald',
  ADD COLUMN IF NOT EXISTS font_body text NOT NULL DEFAULT 'Inter',
  ADD COLUMN IF NOT EXISTS radius_px integer NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS show_pluses boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_how_it_works boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_reviews boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_featured boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS featured_title text NOT NULL DEFAULT 'In evidenza',
  ADD COLUMN IF NOT EXISTS pluses jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS how_steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS social_facebook text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS social_instagram text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS social_tiktok text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS social_youtube text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS custom_pages jsonb NOT NULL DEFAULT '[]'::jsonb;